### ISSUE TITLE
Pleas test before releasing to pub.dev (r >=4.0.0)

### ISSUE THREAD

**Issue by imdatsolak** [zezo357/flutter_meedu_videoplayer#38]
macOS: doesn't compile because Pod-ref is missing or Pod is not in CocoaPods.

**Comment by zezo357** [comment]
> macOS: doesn't compile because Pod-ref is missing or Pod is not in CocoaPods.

I can't test macos, since I don't have a MacBook 

But will do GitHub actions for that case.


And will try to fix the macos error.

Sorry for any inconveniences.

**Comment by imdatsolak** [comment]
Ok, no worries. I went back to 3.x.y for now.

I may be able to test whether it compiles, but currently I don't use your repo for playing videos on macOS, only on Windows. I could, theoretically, switch to using this repo, but as long as I can't compile 🤷🏻

**Comment by MichalNemec** [comment]
Whoops, i just tried to install it, because it looks awesome.

**Comment by zezo357** [comment]
@MichalNemec @imdatsolak can you guys check 4.0.8? 

also check readme for steps for macos and ios.

if there is a problem let me know

**Comment by MichalNemec** [comment]
macos works. sound and fullscreen is broken tho.
ios just cannot get it to run.
first i had issues with
```
Error (Xcode): File not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
```
and now i have issues with wakelock
```
Lexical or Preprocessor Issue (Xcode): 'Flutter/Flutter.h' file not found
/Users/x/.pub-cache/hosted/pub.dev/wakelock-0.6.2/ios/Classes/WakelockPlugin.h:0:8

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.

after fixing that i have, which i cant fix
Analyzing dependencies
make: Nothing to be done for `all'.
make: Nothing to be done for `all'.
[!] CocoaPods could not find compatible versions for pod "media_kit_libs_ios_video":
  In Podfile:
    media_kit_libs_ios_video (from `.symlinks/plugins/media_kit_libs_ios_video/ios`)

Specs satisfying the `media_kit_libs_ios_video (from `.symlinks/plugins/media_kit_libs_ios_video/ios`)` dependency were found, but they required a higher minimum deployment target.
```
these are overrides i did
```
dependency_overrides:
  media_kit:
    git:
      url: https://github.com/zezo357/media_kit
      ref: 6fc3720bea0b162262c9dc48e655b34cfa66903f
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/zezo357/media_kit
      ref: 6fc3720bea0b162262c9dc48e655b34cfa66903f
      path: ./media_kit_video
  media_kit_libs_ios_video:
    git:
      url: https://github.com/zezo357/media_kit
      ref: 6fc3720bea0b162262c9dc48e655b34cfa66903f
      path: ./media_kit_libs_ios_video
  media_kit_native_event_loop:
    git:
      url: https://github.com/zezo357/media_kit
      ref: 6fc3720bea0b162262c9dc48e655b34cfa66903f
      path: ./media_kit_native_event_loop
  media_kit_libs_macos_video:
    git:
      url: https://github.com/zezo357/media_kit
      ref: 6fc3720bea0b162262c9dc48e655b34cfa66903f
      path: ./media_kit_libs_macos_video
  intl: 0.18.0
  visibility_detector: 0.4.0+2
  wakelock: 0.6.2
```
