### ISSUE TITLE
Failed to download package

### ISSUE THREAD

**Issue by JieNengi** [zezo357/flutter_meedu_videoplayer#94]
flutter_meedu_videoplayer:
    git:
      url: https://github.com/zezo357/flutter_meedu_videoplayer

![image](https://github.com/zezo357/flutter_meedu_videoplayer/assets/42732005/903e6b2d-3a72-4fc9-bc51-987532a32b66)

I tried flutter clean。

**Comment by zezo357** [comment]
May I ask why are you using the GitHub branch? And which one so I can test it 

+ I recommend updating to latest flutter release since It fixed alot of bugs related to building media_kit

**Comment by JieNengi** [comment]
> May I ask why are you using the GitHub branch? And which one so I can test it
> 
> * I recommend updating to latest flutter release since It fixed alot of bugs related to building media_kit

use “master”。

pub.dev last version is flutter_meedu_videoplayer: ^4.2.10，No onLongPress that I need 。

**Comment by zezo357** [comment]
Ok got you, 


Did you set the path to package?

**Comment by JieNengi** [comment]
> 

no.

**Comment by zezo357** [comment]
It should be something like this, I don't have access to my development machine right now so I can't get it all

```
dependencies:   
     flutter_meedu_videoplayer:
       git:
         url: https://github.com/zezo357/flutter_meedu_videoplayer
         ref: PR BRANCH NAME 
         path: package 

```

**Comment by JieNengi** [comment]
> It should be something like this, I don't have access to my development machine right now so I can't get it all
> 
> ```
> dependencies:   
>      flutter_meedu_videoplayer:
>        git:
>          url: https://github.com/zezo357/flutter_meedu_videoplayer
>          ref: PR BRANCH NAME 
>          path: package 
> ```

It works fine now, but I haven't found a way to do it with onLongPress.

**Comment by zezo357** [comment]
When I have access to my machine, I will give you the pubspec and how to use it

**Comment by zezo357** [comment]
i have merged the pr it should work with this (you will have to set onLongPressSpeedUp to true in your enabled controls)
```
dependencies:   
     flutter_meedu_videoplayer:
       git:
         url: https://github.com/zezo357/flutter_meedu_videoplayer
         path: package 
```
